# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Wasteland' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wasteland

  target 'WastelandTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WastelandUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
