language: swift
osx_image: xcode11.3
notifications:
  email: false
git:
  depth: 1

before_install:
- ios/decrypt $encrypted_fed384a525d6_key $encrypted_fed384a525d6_iv

install:
- pod install --project-directory=ios/app
- pod install --project-directory=ios/lib/WCore

jobs:
  include:
  - stage: Test
    if: repo = liam923/wasteland
    script:
    - ./ios/test
  - stage: Build
    if: branch = development AND repo = liam923/wasteland
    script:
    - ./ios/build
  - stage: Deploy
    if: branch = master AND repo = liam923/wasteland
    script:
    - ./ios/deploy
