platform :ios, '13.0'

target 'WCore' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'CodableFirebase'

  target 'WCoreTests' do

  end

end
